In [156]:
import socket

In [157]:
ip = '127.0.0.1'
port = 12600

socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.connect((ip, port))
socket.setblocking(True)

In [158]:
cmd = "GetSWParameter, Scan Area Window, SpecLine Size\n"
socket.send(cmd.encode())
socket.recv(1024)

b'5.95034e-08'

In [163]:
cmd = "SetSWParameter, Scan Area Window, SpecLine Angle, 120\n"
socket.send(cmd.encode())
socket.recv(1024)

b'Done'

In [7]:
cmd = 'StartProcedure, Comb Scan'
socket.send(cmd.encode())
socket.recv(1024)

b'Procedure Stopped'

In [19]:
cmd = 'StopProcedure, Comb Scan'
socket.send(cmd.encode())
socket.recv(1024)

b'Done'

In [24]:
cmd = 'PauseProcedure, Comb Scan, AFM, 4'
socket.send(cmd.encode())
socket.recv(1024)

b'Done'

In [153]:
socket.close()

In [32]:
import numpy as np

In [71]:
x = np.zeros((10,10))
x[0] = np.arange(10)
print(x)
x[~np.all(x == 0.0, axis=1)]

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])